/* StaffKeeping – rein lokaler App-Designprototyp · 0.13 */
'use strict';
const screens=['login','register','reset','pending','market'];
const navOnly=document.querySelectorAll('.nav-only'), guests=document.querySelectorAll('.guest-only');
function show(view){if(!screens.includes(view))view='login';screens.forEach(v=>document.getElementById('view-'+v).classList.toggle('hidden',v!==view));const inApp=view==='market';navOnly.forEach(n=>n.classList.toggle('hidden',!inApp));guests.forEach(n=>n.classList.toggle('hidden',inApp));window.scrollTo(0,0);if(view==='market')render();}
document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();show(el.dataset.view)}));
document.getElementById('login-form').addEventListener('submit',e=>{e.preventDefault();show('market')});
document.getElementById('registration-form').addEventListener('submit',e=>{e.preventDefault();show('pending')});
document.getElementById('reset-form').addEventListener('submit',e=>{e.preventDefault();document.getElementById('reset-result').classList.remove('hidden')});
document.querySelectorAll('.pw-toggle').forEach(b=>b.addEventListener('click',()=>{const i=document.getElementById(b.dataset.target);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Anzeigen':'Verbergen'}));
const listings=[
{id:1,title:'Service-Mitarbeitende für Wintersaison',type:'Personal gesucht',branch:'Gastronomie',city:'Luzern',country:'Schweiz',date:'2026-12-01',period:'Dezember – März',stay:true,languages:['DE','EN'],desc:'Verstärkung für Restaurant und Gästebetreuung gesucht.'},
{id:2,title:'Rezeptionistin mit Saisonerfahrung',type:'Personal verfügbar',branch:'Hotellerie',city:'Interlaken',country:'Schweiz',date:'2026-11-15',period:'Ab Mitte November',stay:false,languages:['DE','FR','EN'],desc:'Erfahrene Unterstützung für Front Office und Gästeservice.'},
{id:3,title:'Unterstützung im Housekeeping',type:'Personal gesucht',branch:'Hotellerie',city:'Innsbruck',country:'Österreich',date:'2026-12-10',period:'Dezember – Februar',stay:true,languages:['DE','EN'],desc:'Temporärer Personalbedarf im Housekeeping-Team.'},
{id:4,title:'Küchenteam für Übergangszeit',type:'Personal verfügbar',branch:'Camping',city:'Freiburg',country:'Deutschland',date:'2026-11-01',period:'November – Januar',stay:false,languages:['DE'],desc:'Ein eingespieltes Team für eine befristete Zusammenarbeit.'}
];
const starred=new Set();let favoritesOnly=false,viewMap=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const q=document.getElementById('filter-search').value.toLocaleLowerCase('de'),type=document.getElementById('filter-type').value,branch=document.getElementById('filter-branch').value,stay=document.getElementById('filter-accommodation').checked,date=document.getElementById('filter-date').value;
const items=listings.filter(l=>(!q||[l.title,l.city,l.branch,l.desc].join(' ').toLocaleLowerCase('de').includes(q))&&(!type||l.type===type)&&(!branch||l.branch===branch)&&(!stay||l.stay)&&(!date||l.date>=date)&&(!favoritesOnly||starred.has(l.id)));
document.getElementById('result-count').textContent=items.length+' '+(items.length===1?'Inserat':'Inserate');document.getElementById('bookmark-count').textContent=starred.size;
document.getElementById('listing-grid').innerHTML=items.map(l=>`<article class="listing-card"><div class="listing-top"><span class="type-pill ${l.type==='Personal verfügbar'?'available':''}">${esc(l.type)}</span><button class="star" type="button" data-star="${l.id}" aria-label="${starred.has(l.id)?'Aus Merkliste entfernen':'Zur Merkliste hinzufügen'}" aria-pressed="${starred.has(l.id)}">${starred.has(l.id)?'★':'☆'}</button></div><h3>${esc(l.title)}</h3><div class="listing-location">⌖ ${esc(l.city)} · ${esc(l.country)}</div><p>${esc(l.desc)}</p><div class="listing-meta"><span>◷ ${esc(l.period)}</span>${l.stay?'<span>⌂ Unterkunft</span>':''}</div><div class="listing-footer"><div class="languages">${l.languages.map(s=>`<span>${esc(s)}</span>`).join('')}</div><button class="detail-link" type="button" data-detail="${l.id}">Details ansehen →</button></div></article>`).join('');
document.querySelectorAll('[data-star]').forEach(b=>b.addEventListener('click',()=>{const id=Number(b.dataset.star);starred.has(id)?starred.delete(id):starred.add(id);render()}));document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>{const l=listings.find(x=>x.id===Number(b.dataset.detail));alert('Designprototyp: Die Detailansicht für „'+l.title+'“ wird später umgesetzt.')}));
document.getElementById('no-results').classList.toggle('hidden',items.length>0||viewMap);document.getElementById('listing-grid').classList.toggle('hidden',viewMap);document.getElementById('map-placeholder').classList.toggle('hidden',!viewMap);}
['filter-search','filter-type','filter-branch','filter-date','filter-accommodation'].forEach(id=>document.getElementById(id).addEventListener('input',render));
document.getElementById('filter-reset').addEventListener('click',()=>{['filter-search','filter-type','filter-branch','filter-date'].forEach(id=>document.getElementById(id).value='');document.getElementById('filter-radius').selectedIndex=0;document.getElementById('filter-accommodation').checked=false;favoritesOnly=false;document.getElementById('bookmarks-only').classList.remove('selected');render()});
document.getElementById('bookmarks-only').addEventListener('click',e=>{favoritesOnly=!favoritesOnly;e.currentTarget.classList.toggle('selected',favoritesOnly);render()});
function setView(map){viewMap=map;document.getElementById('list-btn').classList.toggle('active',!map);document.getElementById('map-btn').classList.toggle('active',map);render()};document.getElementById('list-btn').addEventListener('click',()=>setView(false));document.getElementById('map-btn').addEventListener('click',()=>setView(true));
show('login');
