/* StaffKeeping 0.23 – App-Masken inkl. aktualisierter öffentlicher Projektübersicht */
'use strict';
const screens=['login','register','reset','pending','market','profile','my-listings','detail','messages','reviews','admin-businesses','admin-listings','admin-dashboard','admin-docs'];
const navOnly=document.querySelectorAll('.nav-only'), guests=document.querySelectorAll('.guest-only');
const publicViews=new Set(['login','register','reset','pending']);
let demoSignedIn=false;
let skAdmin=false;
let skPending=false;
window.SK_UI={setAccess(isApproved,isAdmin){demoSignedIn=!!isApproved;skAdmin=!!isAdmin;skPending=!isApproved;show(isApproved?'market':'pending',false);},show,logoutView(){demoSignedIn=false;skAdmin=false;skPending=false;show('login',false);}};
function show(view,updateUrl=true){
  if(!screens.includes(view))view='login';
  // Demo-Ansicht: Nur ein explizit gestarteter Demo-Zugang darf interne Seiten sehen.
  if(!demoSignedIn && !publicViews.has(view))view=skPending?'pending':'login';
  if(!skAdmin && view.startsWith('admin-'))view=demoSignedIn?'market':'login';
  if(demoSignedIn && view==='login')view='market';
  screens.forEach(v=>document.getElementById('view-'+v).classList.toggle('hidden',v!==view));
  const inApp=demoSignedIn && !publicViews.has(view);
  navOnly.forEach(n=>n.classList.toggle('hidden',!inApp));
  guests.forEach(n=>n.classList.toggle('hidden',inApp||skPending));
  document.querySelectorAll('.admin-nav, .admin-tabs').forEach(n=>n.classList.toggle('hidden',!skAdmin));
  document.querySelectorAll('.headnav [data-view]').forEach(n=>n.setAttribute('aria-current',n.dataset.view===view?'page':'false'));
  if(updateUrl && location.hash!=='#'+view)history.pushState({view},'', '#'+view);
  window.scrollTo(0,0);
  if(view==='market')render();
  if(view==='my-listings')renderMyListings();
  if(view==='messages')renderChats();
  if(view==='admin-businesses')renderBusinesses();
  if(view==='admin-listings')renderAdminListings();
  if(view==='admin-docs')renderProjectDocs();
}
function logout(){if(window.SK_AUTH) window.SK_AUTH.logout(); else window.SK_UI.logoutView();}
document.addEventListener('click',e=>{
  const el=e.target.closest('[data-view]');if(!el)return;
  e.preventDefault();
  if(el.id==='logout')logout();else show(el.dataset.view);
});
window.addEventListener('popstate',()=>show(location.hash.slice(1)||'login',false));
document.querySelectorAll('.pw-toggle').forEach(b=>b.addEventListener('click',()=>{const i=document.getElementById(b.dataset.target);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Anzeigen':'Verbergen'}));
const listings=[
{id:1,title:'Service-Mitarbeitende für Wintersaison',type:'Personal gesucht',branch:'Gastronomie',city:'Luzern',country:'Schweiz',date:'2026-12-01',period:'Dezember – März',stay:true,languages:['DE','EN'],desc:'Verstärkung für Restaurant und Gästebetreuung gesucht.'},
{id:2,title:'Rezeptionistin mit Saisonerfahrung',type:'Personal verfügbar',branch:'Hotellerie',city:'Interlaken',country:'Schweiz',date:'2026-11-15',period:'Ab Mitte November',stay:false,languages:['DE','FR','EN'],desc:'Erfahrene Unterstützung für Front Office und Gästeservice.'},
{id:3,title:'Unterstützung im Housekeeping',type:'Personal gesucht',branch:'Hotellerie',city:'Innsbruck',country:'Österreich',date:'2026-12-10',period:'Dezember – Februar',stay:true,languages:['DE','EN'],desc:'Temporärer Personalbedarf im Housekeeping-Team.'},
{id:4,title:'Küchenteam für Übergangszeit',type:'Personal verfügbar',branch:'Camping',city:'Freiburg',country:'Deutschland',date:'2026-11-01',period:'November – Januar',stay:false,languages:['DE'],desc:'Ein eingespieltes Team für eine befristete Zusammenarbeit.'}
];
const starred=new Set();let favoritesOnly=false,viewMap=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const q=document.getElementById('filter-search').value.toLocaleLowerCase('de'),type=document.getElementById('filter-type').value,branch=document.getElementById('filter-branch').value,stay=document.getElementById('filter-accommodation').checked,date=document.getElementById('filter-date').value;
const items=listings.filter(l=>(!q||[l.title,l.city,l.branch,l.desc].join(' ').toLocaleLowerCase('de').includes(q))&&(!type||l.type===type)&&(!branch||l.branch===branch)&&(!stay||l.stay)&&(!date||l.date>=date)&&(!favoritesOnly||starred.has(l.id)));
document.getElementById('result-count').textContent=items.length+' '+(items.length===1?'Inserat':'Inserate');document.getElementById('bookmark-count').textContent=starred.size;
document.getElementById('listing-grid').innerHTML=items.map(l=>`<article class="listing-card"><div class="listing-top"><span class="type-pill ${l.type==='Personal verfügbar'?'available':''}">${esc(l.type)}</span><button class="star" type="button" data-star="${l.id}" aria-label="${starred.has(l.id)?'Aus Merkliste entfernen':'Zur Merkliste hinzufügen'}" aria-pressed="${starred.has(l.id)}">${starred.has(l.id)?'★':'☆'}</button></div><h3>${esc(l.title)}</h3><div class="listing-location">⌖ ${esc(l.city)} · ${esc(l.country)}</div><p>${esc(l.desc)}</p><div class="listing-meta"><span>◷ ${esc(l.period)}</span>${l.stay?'<span>⌂ Unterkunft</span>':''}</div><div class="listing-footer"><div class="languages">${l.languages.map(s=>`<span>${esc(s)}</span>`).join('')}</div><button class="detail-link" type="button" data-detail="${l.id}">Details ansehen →</button></div></article>`).join('');
document.querySelectorAll('[data-star]').forEach(b=>b.addEventListener('click',()=>{const id=Number(b.dataset.star);starred.has(id)?starred.delete(id):starred.add(id);render()}));document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>openDetail(Number(b.dataset.detail))));
document.getElementById('no-results').classList.toggle('hidden',items.length>0||viewMap);document.getElementById('listing-grid').classList.toggle('hidden',viewMap);document.getElementById('map-placeholder').classList.toggle('hidden',!viewMap);}
['filter-search','filter-type','filter-branch','filter-date','filter-accommodation'].forEach(id=>document.getElementById(id).addEventListener('input',render));
document.getElementById('filter-reset').addEventListener('click',()=>{['filter-search','filter-type','filter-branch','filter-date'].forEach(id=>document.getElementById(id).value='');document.getElementById('filter-radius').selectedIndex=0;document.getElementById('filter-accommodation').checked=false;favoritesOnly=false;document.getElementById('bookmarks-only').classList.remove('selected');render()});
document.getElementById('bookmarks-only').addEventListener('click',e=>{favoritesOnly=!favoritesOnly;e.currentTarget.classList.toggle('selected',favoritesOnly);render()});
function setView(map){viewMap=map;document.getElementById('list-btn').classList.toggle('active',!map);document.getElementById('map-btn').classList.toggle('active',map);render()};document.getElementById('list-btn').addEventListener('click',()=>setView(false));document.getElementById('map-btn').addEventListener('click',()=>setView(true));
/* Zusätzliche UI-Demoseiten, ohne Backend und ohne dauerhafte Speicherung */
const dialog=document.getElementById('app-dialog');
function modal(title,html){document.getElementById('dialog-title').textContent=title;document.getElementById('dialog-body').innerHTML=html;dialog.showModal();}
document.getElementById('dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
let chosenListing=1, listTab='inserate';const listingStatus=new Map(listings.map(l=>[l.id,'Aktiv']));
const ownListings=[{id:101,title:'Saisonaushilfe im Frühstücksservice',type:'Suche',category:'Service',city:'Luzern',period:'November – Februar',status:'Aktiv'},{id:102,title:'Erfahrene Köchin für Wintersaison',type:'Biete',category:'Küche',city:'Zürich',period:'Dezember – März',status:'Inaktiv'},{id:103,title:'Unterstützung in der Animation',type:'Suche',category:'Animation',city:'Thun',period:'Juni – August',status:'Vergeben'}];
function openDetail(id){const l=listings.find(x=>x.id===id);if(!l)return;chosenListing=id;document.getElementById('detail-title').textContent=l.title;document.getElementById('detail-subtitle').textContent=l.city+' · '+l.country+' · '+l.period;document.getElementById('detail-meta').innerHTML='<span class="type-pill">'+esc(l.type)+'</span><span class="type-pill">'+esc(l.branch)+'</span><span class="type-pill">'+esc(l.period)+'</span>';document.getElementById('detail-description').textContent=l.desc;document.getElementById('detail-features').innerHTML=l.languages.map(x=>'<span class="type-pill">'+esc(x)+'</span>').join('')+(l.stay?'<span class="type-pill">⌂ Unterkunft vorhanden</span>':'');document.getElementById('detail-company').textContent=['Hotel Seeblick','Alpenhof Interlaken','Gastbetrieb Tirol','Camping am Park'][id-1];show('detail');}
document.getElementById('detail-contact').addEventListener('click',()=>modal('Vor dem Kontakt',`<p>Bitte lesen Sie den Kontakt-Disclaimer. Die Zusammenarbeit wird zwischen den Betrieben eigenverantwortlich vereinbart.</p><label class="check"><input type="checkbox" id="disclaimer-accept"><span>Ich habe den Hinweis verstanden.</span></label><div class="dialog-actions"><button class="subtle-btn" type="button" id="dialog-cancel">Abbrechen</button><button class="btn" type="button" id="contact-confirm" disabled>Verstanden – Kontakt aufnehmen</button></div>`));
document.getElementById('detail-reviews').addEventListener('click',()=>modal('Bewertungen des Betriebs','<p>★ 4,5 / 5 · Beispielbewertung</p><p>Gute Kommunikation und zuverlässige Zusammenarbeit.</p>'));
document.getElementById('dialog-body').addEventListener('change',e=>{if(e.target.id==='disclaimer-accept')document.getElementById('contact-confirm').disabled=!e.target.checked});
document.getElementById('dialog-body').addEventListener('click',e=>{if(e.target.closest('#dialog-cancel'))dialog.close();if(e.target.closest('#contact-confirm')){dialog.close();selectedChat=0;show('messages');}if(e.target.closest('#save-demo-listing')){const form=document.getElementById('listing-form');if(!form.reportValidity())return;const id=Number(form.dataset.edit||Date.now());const record={id,title:form.elements.title.value,type:form.elements.type.value,category:form.elements.category.value,city:'Demo-Ort',period:form.elements.from.value+' – '+form.elements.to.value,status:'Aktiv'};const i=ownListings.findIndex(l=>l.id===id);if(i>=0)ownListings[i]=record;else ownListings.unshift(record);dialog.close();renderMyListings();}if(e.target.closest('#submit-demo-review')){const form=document.getElementById('review-form');if(!form.reportValidity())return;dialog.close();modal('Bewertung erfasst','<p>Die Bewertung wurde nur in dieser Designvorschau bestätigt und nicht gespeichert.</p>');}});
function listingForm(id){const l=ownListings.find(x=>x.id===id);modal(l?'Inserat bearbeiten':'Neues Inserat',`<form id="listing-form" data-edit="${l?.id||''}"><div class="field-grid"><div><label>Typ *</label><select name="type" required><option ${l?.type==='Suche'?'selected':''}>Suche</option><option ${l?.type==='Biete'?'selected':''}>Biete</option></select></div><div><label>Kategorie *</label><select name="category">${['Küche','Service','Housekeeping','Technik','Animation'].map(x=>`<option ${l?.category===x?'selected':''}>${x}</option>`).join('')}</select></div></div><label>Titel (5–80 Zeichen) *</label><input name="title" required minlength="5" maxlength="80" value="${esc(l?.title||'')}"><label>Beschreibung (20–1000 Zeichen) *</label><textarea name="description" required minlength="20" maxlength="1000" rows="3">${l?'Vereinbarter temporärer Einsatz mit dem Partnerbetrieb.':''}</textarea><div class="field-grid"><div><label>Von *</label><input name="from" type="date" required value="2026-12-01"></div><div><label>Bis *</label><input name="to" type="date" required value="2027-02-28"></div></div><label>Rahmenbedingungen (max. 500 Zeichen)</label><textarea maxlength="500" rows="2"></textarea><label class="check"><input type="checkbox"><span>Unterkunft vorhanden</span></label><p class="muted">Sprachen: <label class="inline-check"><input type="checkbox" checked> DE</label> <label class="inline-check"><input type="checkbox"> FR</label> <label class="inline-check"><input type="checkbox"> IT</label> <label class="inline-check"><input type="checkbox"> EN</label> <label class="inline-check"><input type="checkbox"> ES</label></p><div class="dialog-actions"><button type="button" class="btn" id="save-demo-listing">Demo-Inserat übernehmen</button></div></form>`);}
document.getElementById('new-listing').addEventListener('click',()=>listingForm());
document.querySelectorAll('[data-list-tab]').forEach(b=>b.addEventListener('click',()=>{listTab=b.dataset.listTab;document.querySelectorAll('[data-list-tab]').forEach(x=>x.classList.toggle('active',x===b));renderMyListings()}));
function renderMyListings(){const rows=listTab==='inserate'?ownListings.filter(x=>!['Vergeben','Abgeschlossen'].includes(x.status)):ownListings.filter(x=>x.status==='Vergeben'||x.status==='Abgeschlossen');document.getElementById('my-list-table').innerHTML='<h2>'+(listTab==='inserate'?'Eigene Inserate':listTab==='vergeben'?'Vergebene Inserate':'Partnerschaften als Partner')+'</h2>'+(listTab==='partner'?'<p class="muted">In der Demo werden beispielhaft vergebene Inserate angezeigt.</p>':'')+'<div class="table-wrap"><table class="data-table"><thead><tr><th>Inserat</th><th>Typ / Kategorie</th><th>Zeitraum</th><th>Status</th><th>Aktionen</th></tr></thead><tbody>'+rows.map(l=>`<tr><td><strong>${esc(l.title)}</strong><small>${esc(l.city)}</small></td><td>${esc(l.type)} · ${esc(l.category)}</td><td>${esc(l.period)}</td><td><span class="status-tag">${esc(l.status)}</span></td><td class="table-actions"><button data-own="edit" data-id="${l.id}">✎</button><button data-own="toggle" data-id="${l.id}">↻</button><button data-own="assign" data-id="${l.id}">🤝</button><button data-own="review" data-id="${l.id}">★</button><button data-own="messages" data-id="${l.id}">✉</button><button data-own="delete" data-id="${l.id}">✕</button></td></tr>`).join('')+'</tbody></table></div>'+(rows.length?'':'<p class="muted">Keine Inserate in dieser Ansicht.</p>');}
document.getElementById('my-list-table').addEventListener('click',e=>{const b=e.target.closest('[data-own]');if(!b)return;const id=Number(b.dataset.id),l=ownListings.find(x=>x.id===id);if(!l)return;switch(b.dataset.own){case'edit':listingForm(id);break;case'toggle':l.status=l.status==='Aktiv'?'Inaktiv':'Aktiv';renderMyListings();break;case'delete':if(confirm('Demo-Inserat aus der aktuellen Ansicht entfernen?')){ownListings.splice(ownListings.indexOf(l),1);renderMyListings()}break;case'assign':modal('Inserat vergeben','<p>Wählen Sie einen Partner aus bestehenden Konversationen (Demodaten).</p><label>Partner</label><select id="assign-partner"><option>Hotel Seeblick</option><option>Restaurant Seeblick</option></select><div class="dialog-actions"><button type="button" class="btn" id="confirm-assign">Vergeben</button></div>');document.getElementById('confirm-assign').addEventListener('click',()=>{l.status='Vergeben';dialog.close();renderMyListings()});break;case'review':modal('Bewertung abgeben',`<form id="review-form"><label>Kommunikation *</label><select required><option value="">Bitte wählen</option>${[1,2,3,4,5].map(n=>'<option>'+n+' ★</option>').join('')}</select><label>Zuverlässigkeit *</label><select required><option value="">Bitte wählen</option>${[1,2,3,4,5].map(n=>'<option>'+n+' ★</option>').join('')}</select><label class="check"><input type="checkbox"><span>Weiterempfehlung</span></label><label>Kommentar</label><textarea rows="3"></textarea><div class="dialog-actions"><button class="btn" type="button" id="submit-demo-review">Bewertung abschicken</button></div></form>`);break;case'messages':show('messages');break;}});
const chats=[{name:'Hotel Sonnenblick',topic:'Service-Mitarbeitende für Wintersaison',messages:[['other','Guten Tag, wir interessieren uns für einen Austausch.'],['mine','Vielen Dank für die Anfrage! Gerne besprechen wir Details.']]},{name:'Camping am Park',topic:'Küchenteam für Übergangszeit',messages:[['other','Guten Morgen, wäre eine Zusammenarbeit im Dezember möglich?']]}];let selectedChat=0;
function renderChats(){document.getElementById('conversation-buttons').innerHTML=chats.map((c,i)=>`<button class="conversation-btn ${i===selectedChat?'active':''}" data-chat="${i}"><strong>${esc(c.name)}</strong><small>${esc(c.topic)}</small></button>`).join('');const c=chats[selectedChat];document.getElementById('chat-heading').innerHTML='<strong>'+esc(c.name)+'</strong><small>'+esc(c.topic)+'</small>';document.getElementById('chat-history').innerHTML=c.messages.map(([who,message])=>'<div class="bubble '+who+'">'+esc(message)+'</div>').join('');}
document.getElementById('conversation-buttons').addEventListener('click',e=>{const b=e.target.closest('[data-chat]');if(b){selectedChat=Number(b.dataset.chat);renderChats()}});document.getElementById('chat-form').addEventListener('submit',e=>{e.preventDefault();const field=document.getElementById('chat-entry');chats[selectedChat].messages.push(['mine',field.value]);field.value='';renderChats()});
document.getElementById('profile-form').addEventListener('submit',e=>{e.preventDefault();document.getElementById('profile-info').classList.remove('hidden');document.getElementById('profile-info').textContent='Designvorschau: Änderungen werden nicht auf einem Server gespeichert.'});
const companies=[{name:'Alpenhotel Panorama',land:'Schweiz',status:'Ausstehend'},{name:'Restaurant Seeblick',land:'Schweiz',status:'Ausstehend'},{name:'Camping am Park',land:'Deutschland',status:'Aktiv'},{name:'Hotel Tirol',land:'Österreich',status:'Aktiv'}];
function renderBusinesses(){
 const root=document.getElementById('admin-business-table');
 if(!skAdmin){root.textContent='Nur für Administratoren.';return;}
 if(!window.SK_AUTH){root.textContent='Supabase-Verbindung wird geladen …';return;}
 root.textContent='Unternehmen werden geladen …';
 window.SK_AUTH.loadBusinesses().then(rows=>{
  root.innerHTML='<div class="table-wrap"><table class="data-table"><thead><tr><th>Betrieb</th><th>Land</th><th>Status</th><th>Aktionen</th></tr></thead><tbody>'+rows.map(c=>`<tr><td>${esc(c.company_name)}</td><td>${esc(c.country)}</td><td>${esc(c.status)}</td><td><button data-real-business="${esc(c.id)}" data-status="Freigeschaltet">Freischalten</button> <button data-real-business="${esc(c.id)}" data-status="Gesperrt">Sperren</button></td></tr>`).join('')+'</tbody></table></div>';
 }).catch(e=>root.textContent='Laden fehlgeschlagen: '+e.message);
}
document.getElementById('admin-business-table').addEventListener('click', async e=>{
 const b=e.target.closest('[data-real-business]'); if(!b||!skAdmin||!window.SK_AUTH)return;
 const status=b.dataset.status;
 if(!confirm('Unternehmen wirklich auf '+status+' setzen?'))return;
 b.disabled=true;
 try{await window.SK_AUTH.setBusinessStatus(b.dataset.realBusiness,status);renderBusinesses();}catch(err){alert('Freigabe fehlgeschlagen: '+err.message);b.disabled=false;}
});
function renderAdminListings(){const country=document.getElementById('admin-country').value,status=document.getElementById('admin-status').value;const filtered=listings.filter(l=>(!country||l.country===country)&&(!status||listingStatus.get(l.id)===status));document.getElementById('admin-listing-table').innerHTML='<div class="table-wrap"><table class="data-table"><thead><tr><th>Inserat</th><th>Land</th><th>Status</th><th>Aktionen</th></tr></thead><tbody>'+filtered.map(l=>`<tr><td>${esc(l.title)}</td><td>${esc(l.country)}</td><td><span class="status-tag">${esc(listingStatus.get(l.id))}</span></td><td class="table-actions"><button data-moderate="${l.id}" data-action="edit">Bearbeiten</button><button data-moderate="${l.id}" data-action="toggle">${listingStatus.get(l.id)==='Aktiv'?'Sperren':'Aktivieren'}</button></td></tr>`).join('')+'</tbody></table></div>';}
document.getElementById('admin-listing-table').addEventListener('click',e=>{const b=e.target.closest('[data-moderate]');if(!b)return;const id=Number(b.dataset.moderate);if(b.dataset.action==='toggle'){listingStatus.set(id,listingStatus.get(id)==='Aktiv'?'Gesperrt':'Aktiv');renderAdminListings()}else{const l=listings.find(x=>x.id===id);modal('Inserat prüfen','<p><strong>'+esc(l.title)+'</strong></p><p>'+esc(l.desc)+'</p><p class="muted">Bearbeitung und dauerhafte Löschung folgen mit Backend und Berechtigungsprüfung.</p>')}});
['admin-country','admin-status'].forEach(id=>document.getElementById(id).addEventListener('change',renderAdminListings));
show('login',false);

/* Projektdokumentation – nur bewusst öffentlichkeitsfähiger Auszug.
   Vollständiges Originalkonzept nicht in öffentlich ausgelieferte Assets integrieren. */
const projectChapters = {
briefing: ['Projektbriefing', `StaffKeeping ist eine B2B-Applikation für partnerschaftlichen Personalaustausch zwischen Betrieben der Hotellerie, Gastronomie und Campingbranche im DACH-Raum. Die bestehende Marketing-Website ist separat und verlinkt künftig auf die Anwendung.\n\nEinstieg: Login oder Selbstregistrierung. Neue Unternehmen werden erst nach administrativer Prüfung freigegeben. Der Marktplatz ist der Startpunkt nach erfolgreichem Login.\n\nBubble dient als Quelle für Geschäftsabläufe und Datenmodell, NICHT als Designvorlage. Die bestehende CI ist im Migrationskonzept Kapitel 13 dokumentiert.`],
concept: ['Systemkonzept / Architektur', `Stand: technisches Zielkonzept, noch NICHT umgesetzt.\n\nFrontend: GitHub Pages, öffentlich aufrufbar; geschützte Anwendungsdaten ausschliesslich nach Authentifizierung und Berechtigung. Quellcode im Browser ist öffentlich sichtbar.\nBackend: separates Supabase-Projekt mit PostgreSQL, Auth, RLS, Storage und gegebenenfalls Edge Functions. Intern-only-Tabellen möglichst in nicht exponierten Schemas.\nZugriff: Unternehmen sehen berechtigte Daten; Chats dürfen Teilnehmer und berechtigte Administratoren lesen. Für Administratoren ist eine lesende Chat-Einsicht vorgesehen.\nSicherheit: RLS ist zwingend auch bei direkten API-Anfragen; Service-/Secret-Keys bleiben ausschliesslich serverseitig. Keine zusätzliche Feldverschlüsselung geplant; Supabase-Standardschutz plus Berechtigungen.\nDatenmigration: Optional ausgewählte allgemeine Stammdaten; alte Bubble-Testkonten, Inserate, Chats, Bewertungen nicht übernehmen.\nExterne Dienste: Google Maps, E-Mail-Dienst; Stripe erst nach fachlicher Freigabe.\nDie detaillierten Tabellen-, Workflow- und UI-Spezifikationen stehen im vollständigen Original-Migrationskonzept 2.2, das erst mit einem geschützten Dokumentdienst in der Admin-Ansicht verfügbar gemacht wird.`],
status: ['Aktueller Entwicklungsstand', `Release: 0.22 – Auth-Weiterleitung korrigiert; Registrierung noch erneut live testen.\nEcht angebunden seit 0.20: Supabase E-Mail/Passwort-Login, Registrierung, Firmenfreigabe und Admin-Berechtigungsprüfung. Supabase-Tabellen, RLS und Administrator wurden installiert und SQL-seitig überprüft.\nPostmark: DKIM, Return-Path, Kontofreigabe und Custom SMTP eingerichtet; Recovery-Mail wurde zugestellt (Spam-Ordner). Spam-Einstufung noch prüfen.\n0.21: Passwort-Recovery mit neuem Passwort, Logout und erneutem Login vom Benutzer erfolgreich live getestet. 0.22: Signup-/Recovery-Redirect wird aus dem echten App-Skriptpfad /staffkeeping/ statt aus der aktuellen Browser-URL abgeleitet.\nNoch Demo: Inserate, Nachrichten, Profiländerungen, Bewertungen und nicht angebundene Fachfunktionen. Originalkonzept weiterhin nicht öffentlich abrufbar.\nOffen: Bestätigungsmail-Weiterleitung und Firma nach Bestätigung erneut testen, RLS-Negativtests mit zwei Firmen, Registrierungsfortsetzung über Geräte, Spam-Zustellung und geschützte Projektdokumentation.`],
issues: ['TODO und zu klärende Punkte', `PRIO 0 – 0.22 live testen: Signup-Link muss redirect_to mit /staffkeeping/ enthalten; Mail-Bestätigung und Registrierung durchspielen. Recovery-Test 0.21 wurde live bestanden.\nPRIO 0 – Zwei Testunternehmen: Registrierung, E-Mail-Bestätigung, Status Ausstehend, Adminfreigabe und Zugriffsgrenzen per RLS/API testen.\nPRIO 0 – Geschützte Originaldokumente erst nach serverseitiger Adminfreigabe bereitstellen; öffentliche Projektübersicht bleibt ohne Geheimnisse.\nPRIO 1 – Registrierung über anderes Gerät zuverlässig fortsetzen; Nutzungsbedingungen vor Produktivstart finalisieren.\nPRIO 1 – Designabnahme mit Annette: Original-Logo, Schriftart, exakter Blauton, Navigation.\nPRIO 1 – Bubble-Fachworkflows mit Migrationskonzept vergleichen.\nPRIO 2 – Inserate, Chat, Karten, Benachrichtigungen real anbinden; Stripe erst später.\nÜbergabe an Annette: Domains, Postmark, GitHub/Supabase-Eigentum und Administratorrechte gemäss Checkliste.`],
rules: ['Verbindliche Entwicklungs- und Release-Regeln', `1. Vor einer Änderung Konzept, Entwicklungsstand, TODO, Regeln und betroffene Funktionen prüfen; erst nach Freigabe „LOS“ implementieren.\n2. Nur Anwendung bauen; die separate Marketing-Homepage bleibt unverändert.\n3. CSS ausschliesslich zentral in styles/tokens.css und styles/main.css; kein Inline-CSS oder style-Block. Javascript separat.\n4. ZIP-Name: sk-update-<Version>-<YYYYMMDD-HHMMSS>.zip; reale lokale Zeit, passende Versionsnummer.\n5. ZIP-Inhalt: ausschliesslich neue oder geänderte Dateien unter dem Wurzelverzeichnis staffkeeping/; keine Repo-Root-Dateien.\n6. staffkeeping/_bubble/ ist lokales Referenzarchiv, mit .gitignore ausgeschlossen; keine automatische Synchronisierung.\n7. Bei JEDEM Release Konzept-/Status-/Aufgaben-/Entscheidungs-/Test-/Versionsdokumentation konsistent aktualisieren. Offen/Geplant/Implementiert/Getestet strikt unterscheiden.\n8. Login, Berechtigungen und vertrauliche Daten ausschliesslich serverseitig absichern; GitHub-Pages-Dateien grundsätzlich als öffentlich betrachten.\n9. Niemals Passwörter, private Schlüssel, Service-Keys oder vertrauliche Dokumente ins Git-Frontend.\n10. Keine unnötigen Fachlogikänderungen; offene Fragen explizit kennzeichnen; Tests vor Freigabe dokumentieren.`],
tests: ['Tests / Abnahme', `0.21 – Vom Anwender live bestätigt: Recovery-Mail erhalten, Passwort erfolgreich geändert, Logout und erneuter Login erfolgreich. 0.22 – Redirect-Code statisch geprüft, neue Signup-Mail und Live-Redirect noch nicht getestet.\nRecovery-Test: E-Mail anfordern, Link aus Postmark öffnen, Passwortformular sehen (nicht Marktplatz), zwei Passwortfelder prüfen, speichern, ausloggen, mit neuem Passwort anmelden.\nFehlerfälle: Passwörter verschieden, ungültiger/abgelaufener Link, Link in anderem Browser, Reload während Recovery.\n0.20/DB: Adminlogin, Registrierung, Firmenfreigabe und Rollen/RLS mit zwei Benutzern separat nachweisen.\nAlle übrigen Funktionsmasken noch Demo; keine Produktivabnahme behaupten.`],
history: ['Versions- und Entscheidungsverlauf', `0.10–0.18: App-Design, zentrale CSS-Dateien, App-Masken, Admin-Projektdoku.\n0.19: Supabase-Basisschema, RLS und Rollen erstellt; später live vom Anwender installiert und SQL-seitig geprüft.\n0.19.1–0.19.2: Übergabeplanung und nachgeliefertes Migrationspaket.\n0.20: Echte Supabase-Authentifizierung, Firmenregistrierung und Adminfreigabe angebunden.\n0.21: Recovery und erneuter Login live erfolgreich getestet. 0.22: Auth-Callback-URL stabil aus Skriptpfad abgeleitet; Registrierung/Reset auf /staffkeeping/ statt Domain-Root; Live-Test offen. 0.23: Fehlenden Firmen-Datensatz nach bestätigter E-Mail im bestehenden Benutzerkonto über Registrierungsmaske ergänzen; Live-Test offen.\nPostmark 09.10.: DKIM, Return-Path, Accountfreigabe und Supabase-SMTP vom Anwender eingerichtet.\nRegeln: Nur App; zentrale CSS-Dateien; ZIP nur neue/geänderte Dateien unter staffkeeping/; Doku in jedem Release nachführen.`],
handoff: ['Übergabe an einen neuen Chat', `StaffKeeping Stand 0.23 / 09.10.2026. Repo: staffkeeping/; GitHub-Pages-App mit Supabase Auth seit 0.20, echtes Admin-Konto vorhanden, Grundschema/RLS installiert und SQL-geprüft.\nPostmark: mueller-home.me DKIM und Return-Path bestätigt, Freigabe und SMTP konfiguriert; Recovery-Mail zugestellt (Spam), Zustellbarkeit noch prüfen.\n0.21 Recovery inkl. neuem Passwort und erneutem Login vom Anwender erfolgreich live getestet. 0.22: Signup-Link enthielt fälschlich redirect_to=https://www.mueller-home.me/; Code für Registrierung und Reset nun auf App-Basis /staffkeeping/ umgestellt. Neuer Live-Test ausstehend. 0.23: Bestätigter Auth-Benutzer ohne Firma wird nun zum Ergänzen der Firmendaten geführt (kein erneutes signUp/keine neue Mail); Live-Test ausstehend.\n0.23: Beim Live-Test war die Test-E-Mail bestätigt, aber die SQL-Abfrage lieferte keine Firma; bisher wurde nur die Warteseite angezeigt. Jetzt Firmenregistrierung fortsetzen, Daten erfassen und Status Ausstehend/Administratorfreigabe testen. Live-Retest offen. Fachmasken (Inserate, Chats, Bewertungen etc.) sind weiter Demo. Admin-Dokumentation ist gekürzt, vollständiges Originalkonzept lokal in gitignoriertem _bubble/; nicht über öffentliche Pages veröffentlichen.\nNächste Arbeit: 0.23 installieren, mit bereits bestätigtem Testkonto anmelden, Firmendaten ohne erneute E-Mail vervollständigen, Status Ausstehend prüfen; anschliessend Admin-Freigabe und RLS-Negativtests mit zwei Unternehmen durchführen.\nVerbindlich: docs/entwicklungsregeln.md lesen; ZIP sk-update-<Version>-<YYYYMMDD-HHMMSS>.zip, nur geänderte/neue Dateien unter staffkeeping/; alle Doku mitführen. Übergabe an Annette in docs/uebergabe-annette.md.`],
ownership: ['Übergabe an Annette · Betrieb & Eigentum', `BESCHLOSSEN, ABER NOCH NICHT AUSGEFÜHRT (Stand 0.19.1).\n\nGitHub: Bestehendes Repository an Annette oder ihre Organisation übertragen; bisheriger Entwickler bleibt zusätzlicher Admin. Rollen und GitHub-Pages-Betrieb prüfen.\nSupabase: Bestehendes Projekt in Annettes Organisation überführen; Adminzugang für Entwickler erhalten, Billing und Backups prüfen.\nPostmark: Bestehendes Konto/Server in Annettes Verantwortung übergeben; zusätzliches Adminrecht, Sender-Domain, SPF/DKIM/DMARC und Mailzustellung klären.\nGoogle Maps: Vorhandener API-Key gehört bereits Annette; beibehalten, Domain-Referrer und API-Beschränkung prüfen.\nDomain: App auf Annettes Domain umstellen, bestehende Marketingseite verlinkt dorthin. DNS/HTTPS und Supabase Auth Redirect-/Site-URLs entsprechend ändern.\nSicherheit: Secrets nicht im Frontend hinterlegen; Schlüssel bei Bedarf wechseln; Testdaten vor Go-live kontrolliert bereinigen; Auth, RLS, Chats und Rechte auf finaler Domain testen.\nVollständige, versionierte Checkliste: docs/uebergabe-annette.md. Keine echte Übertragung oder Einrichtung ist durch diese Dokumentation erfolgt.`],
original: ['Vollständiges Migrationskonzept', `Quelle: staffkeeping_migrationskonzept.html, Version 2.2 vom 14.09.2026 (umfangreiches Original mit Screenshots, SQL-Konzept, Privacy Rules, Workflows und UI-Spezifikation).\nDieses Dokument wird bewusst NICHT in GitHub-Pages-Assets oder in den öffentlichen JavaScript-Code kopiert. Ein Demo-Login ist kein Sicherheitsmechanismus.\nBis das sichere Supabase-Dokumentenbackend mit Adminrolle existiert, Original bitte ausschliesslich lokal unter staffkeeping/_bubble/ verwahren. Zur Einsicht das Original lokal öffnen.\nSpäter: Backend liefert das Dokument nur an authentifizierte Administratoren, mit serverseitiger Rollenprüfung.\nDie übrigen Kapitel dieser Ansicht sind eine konsolidierte Arbeitszusammenfassung, KEIN Ersatz für die vollständige Originalquelle.`]
};
let currentDoc='briefing';
function renderProjectDocs(){const item=projectChapters[currentDoc];if(!item)return;document.getElementById('doc-heading').textContent=item[0];document.getElementById('doc-body').textContent=item[1];document.querySelectorAll('[data-doc]').forEach(b=>{b.classList.toggle('active',b.dataset.doc===currentDoc);b.setAttribute('aria-current',b.dataset.doc===currentDoc?'true':'false')});}
document.querySelectorAll('[data-doc]').forEach(b=>b.addEventListener('click',()=>{currentDoc=b.dataset.doc;renderProjectDocs();}));
document.getElementById('copy-doc').addEventListener('click',async()=>{const [title,body]=projectChapters[currentDoc];try{await navigator.clipboard.writeText(title+'\n\n'+body);document.getElementById('doc-copy-info').textContent='Kapitel kopiert.';}catch(e){document.getElementById('doc-copy-info').textContent='Kopieren nicht verfügbar. Bitte Text im Kapitel markieren und kopieren.';}});
