-- StaffKeeping 0.32.2.1: central documentation + integrated handbook.
-- 1 transaction containing 2 UPDATEs, followed by 1 verification SELECT.
BEGIN;
UPDATE sk_internal.project_doc_chapters
SET body=body || E'\n\n' || $doc$## Marktplatzrollen und Suche 0.32.2.1
Verbindliche Trennung: Die Staff-Admin-Rolle berechtigt zum Einsehen veröffentlichter Inserate freigegebener Betriebe, aber niemals von sich aus zur Marktteilnahme. Inserate erstellen, ändern, aktivieren/deaktivieren, löschen, Kontaktanfragen stellen und Unterhaltungen führen benötigen immer eine eigene aktive/freigegebene Betriebsmitgliedschaft. Administratoren mit eigenem freigegebenem Betrieb handeln im Marktplatz nur im Namen dieses Betriebs und behalten separat ihre Admin-Rechte. Die Schreib-RLS auf public.sk_listings verlangt bereits Mitgliedschaft und Freigabe; die SELECT-RLS wurde für administrative Einsicht erweitert. Zusätzliche Chat- und Kontakt-RLS erst bei Einführung von 0.32.3 analog implementieren und testen. Die normale Suche blendet eigene Inserate anhand der Betriebs-ID aus; eigene Inserate bleiben unter Meine Inserate verwaltbar. Reiner Admin sieht fremde veröffentlichte Inserate. Keine fiktive Unterhaltung als echte Funktion ausweisen.
Testfälle: (1) reiner Admin sieht veröffentlichte Fremdinserate, keine eigenen Aktionen; (2) Admin mit Betrieb kann nur als eigener Betrieb Inserate verwalten; (3) eigener Betrieb erscheint nicht in Marktplatzsuche; (4) zweiter Betrieb sieht aktives Inserat; (5) nicht freigegebenes Mitglied kann keine Inserate schreiben; (6) direkte REST INSERT/UPDATE/DELETE mit reinem Admin muss an RLS scheitern. Umkreissuche 0.32.2.1: Entfernungen werden über SECURITY DEFINER-RPC sk_marketplace_distances berechnet, ohne fremde Koordinaten an den Browser zu übermitteln. Grundlage ist der freigegebene eigene Betriebsstandort mit gültigen Koordinaten. Verfügbare Radien: 10, 25, 50, 100, 200 km sowie alle Entfernungen. Bei aktivem Radius erscheinen Inserate innerhalb des Radius zuerst sortiert nach Entfernung, danach Inserate ohne verifizierte Koordinaten separat mit Hinweis Entfernung nicht berechenbar. Bekannte Inserate ausserhalb Radius verschwinden. Hat der Suchende selbst keinen gültigen Standort (insbesondere reiner Admin), wird der Radius nicht angewandt und ein klarer Hinweis gezeigt. Noch offen: Suche von frei wählbarem Ort, Kartenansicht, Kontaktaufnahme 0.32.3, API-Rollentests live. Sicherheit/TODO mit Annette: Google-Maps-API-Key in scripts/maps-config.js (GitHub Secret Scan) im Google-Cloud-Konto auf HTTP-Referrer, API-Limits und Nutzung prüfen; Nutzer besitzt keinen Account-Zugriff. Nicht als behoben markieren.
$doc$, updated_at=now()
WHERE slug='concept' AND position('## Marktplatzrollen und Suche 0.32.2.1' in body)=0;
UPDATE sk_internal.help_chapters
SET body=body || E'\n\n' || $help$## Rollen und eigene Inserate (0.32.2.1)
Im Marktplatz werden Inserate des eigenen Betriebs nicht angezeigt. Eigene Inserate sind unter Meine Inserate zu verwalten. Administratoren ohne eigenen freigegebenen Betrieb können Inserate ansehen, aber keine eigenen Inserate erstellen oder Unterhaltungen führen. Ein Administrator mit eigenem freigegebenen Betrieb kann die Betriebsfunktionen wie andere Betriebe benutzen; seine Admin-Rechte bleiben davon getrennt. Kontaktaufnahme und echte Unterhaltungen folgen in einer späteren Version. Umkreissuche: Von gültigen Standortkoordinaten des eigenen freigegebenen Betriebs; Inserate ohne überprüfbare Koordinaten stehen am Ende mit klarer Kennzeichnung, bekannte Inserate ausserhalb des Radius entfallen. Ohne eigenen verifizierten Standort wird kein Radiusfilter angewandt und ein Hinweis eingeblendet.
Screenshot-Platzhalter: ![Marktplatz ohne eigene Inserate](screenshot:market-roles-03221)
$help$, updated_at=now()
WHERE page_key='market' AND position('## Rollen und eigene Inserate (0.32.2.1)' in body)=0;
COMMIT;
SELECT 'StaffKeeping 0.32.2.1 – Dokumentationsmigration ausgeführt' AS status;
