-- StaffKeeping 0.33.1: existing centralized documentation only.
-- TWO UPDATEs in one transaction; one final SELECT. Supabase may display only the final resultset.
BEGIN;
UPDATE sk_internal.project_doc_chapters SET body=body || E'\n\n' || $doc$## StaffKeeping 0.33.1 – Mehrbetriebsverwaltung und manuelle Stufe-2-Freigabe
Kundenkonto, Betrieb und Abonnement sind getrennte Konzepte. Jeder Betrieb muss von Annette separat freigegeben werden. Neue Betriebe werden ohne neues Login unter „Meine Betriebe“ erfasst und erhalten zunächst eine eigenständige Kundenkonto-Zuordnung. Es gibt KEINE automatische Abo-Übernahme aus gleicher E-Mail, Name, UID oder Kontaktperson. Bei bestehenden Benutzerkonten kann ein weiterer Betrieb hinzugefügt werden. Alte UNIQUE(user_id)-Mitgliedschaftsbeschränkung wird entfernt. Im Formular „Neues Inserat“ wählt der Benutzer ausschliesslich aus seinen FREIGEGEBENEN Betrieben; eigene Inserate sind betriebsübergreifend in Meine Inserate sichtbar. Noch nicht umgesetzt: Standortauswahl für Radius über mehrere Betriebe, vollständige Profilbearbeitung je Betrieb, Einladungen anderer Benutzer, Betriebskonto-Zusammenführung, Chat.
Freigabe Stufe 1: Nur Annette kann einzelnen Betrieb freigeben. Stufe 2: Später Abonnement ODER manuelle Nutzungsfreigabe am Kundenkonto. Abonnements inklusive Zahlung/Abrechnung sind NICHT produktiv. Neue interne Tabelle customer_manual_access: Grund, Beginn, optional Ablauf, Widerruf; jede manuelle Änderung in customer_manual_access_audit. RPCs sk_admin_set_manual_access und sk_admin_manual_access_overview sind strikt admin-only; interne Tabellen im nicht exponierten Schema. Widerruf der manuellen Freigabe darf gültiges Bezahl-Abo nicht annullieren. DER STUFE-2-GATE IST NOCH NICHT AKTIV, daher beeinflusst eine manuelle Freigabe in 0.33.1 noch keinen Zugriff. Spätere Einführung bedarf Migration, Freischaltung bestehender Testkonten und umfassender RLS-/RPC-Tests. Annette legt Kriterien für Zusammenführung/Abos selbst fest; gleiche Anmeldung belegt keine Abo-Zugehörigkeit.
Tests: Migration nur einmal ausführen (0.33.0 integriert); check counts und UNIQUE-Constraint=0; Anmeldung altes Konto, Inserate unverändert; weiteren Betrieb anlegen, gesondert freigeben; Inserat Betriebsauswahl, auch Edit/Toggling/Entfernung mit korrekter Zugehörigkeit; Admin ohne Betrieb keine Markt-Aktionen; manuelle Freigabe mit Grund/Frist, ändern/widerrufen, Audit prüfen; bei Abo-Sperre keine Veränderung feststellen, da inaktiv. TODO: Profilbearbeitung pro Betrieb, Mehrbenutzer-Einladungen, Abomodell und Chat; Google-Maps-API-Key mit Annette auf Referrer/API-Einschränkungen prüfen.
$doc$,updated_at=now()
WHERE slug='concept' AND position('## StaffKeeping 0.33.1 – Mehrbetriebsverwaltung' IN body)=0;
UPDATE sk_internal.help_chapters SET body=body || E'\n\n' || $doc$## Mehrere Betriebe und manuelle Nutzungsfreigaben · 0.33.1
Über „Meine Betriebe“ sehen berechtigte Benutzer ihre Betriebe und können einen weiteren Betrieb zur Prüfung erfassen. Jeder benötigt eine eigene Freigabe durch Annette. Bei „Meine Inserate“ kann beim Erstellen zwischen freigegebenen Betrieben gewählt werden. Admin → Betriebe: Manuelle Nutzungsfreigabe je Kundenkonto, mit Grund, Frist oder unbefristet, kann später wieder widerrufen werden. Noch keine Bezahlfunktion oder aktive Abo-Sperre; Freigabe 2 ist nur für spätere Einführung vorbereitet. Andere Mitarbeiter einladen und Chat stehen noch aus. ![Mehrere Betriebe](screenshot:multi-businesses-0331) ![Kundenkonto-Freigabe](screenshot:manual-account-access-0331)
$doc$,updated_at=now()
WHERE page_key='my-listings' AND position('## Mehrere Betriebe und manuelle Nutzungsfreigaben · 0.33.1' IN body)=0;
COMMIT;
SELECT '0.33.1 Dokumentation aktualisiert' AS result;
