-- StaffKeeping 0.32.2.2 – 2 UPDATEs in 1 Transaktion, 1 Kontroll-SELECT.
BEGIN;
UPDATE sk_internal.project_doc_chapters SET body=body || E'\n\n' || $doc$## Inseratslaufzeit und Marktplatzsichtbarkeit 0.32.2.2
Fachregel: Nicht das Startdatum, sondern das Enddatum entscheidet ueber die zeitliche Gueltigkeit. Ein Inserat ist veroeffentlicht, wenn status=Aktiv, date_to >= heutiges Datum in Europe/Zurich, Eigentuerbetrieb freigegeben und fuer Betrachter nicht eigener Betrieb. Zukuenftiger Beginn ist ebenso erlaubt wie bereits vergangener Beginn. Nach Ende wird status=Abgelaufen durch stuendlichen Datenbankjob gesetzt; RLS verbietet die oeffentliche Anzeige sofort beim Tageswechsel auch ohne Job. Meine Inserate zeigt Abgelaufen separat vom manuell gesetzten Inaktiv. Nach Verlaengerung des Enddatums wird ein abgelaufenes Inserat Inaktiv und muss bewusst reaktiviert werden. Enddaten werden als DD.MM.YYYY angezeigt, in der Datenbank ISO-Datum gespeichert.
Marktplatz-Befund: Bereits Version 0.32.2.1 filterte nach date_to >= heute, nicht nach date_from. Das fehlende Fremdinserat fuer einen neu genehmigten Betrieb ist deshalb NICHT durch das zukuenftige Startdatum erklaert. Der Kontroll-SELECT der Migration zeigt Status und Freigaben; Korrektur: Die RLS-Sichtbarkeit fremder Inserate prueft nun die Freigabe des Inseratsbetriebes separat von der Mitgliedschaft des Betrachters, mit sk_listing_owner_is_approved(). Die bisherige Verwendung von sk_is_approved_member() fuer den Fremdbetrieb konnte einen unberechtigten Ausschluss verursachen; diese Ursache ist plausibel, aber live noch nicht bestaetigt. Gezielten Zweitbetriebstest nach Migration durchfuehren.
Tests: (1) Start gestern und Ende morgen sichtbar; (2) Start morgen, Ende spaeter sichtbar; (3) Ende gestern Abgelaufen, nicht im Marktplatz; (4) manuelles Inaktiv bleibt inaktiv; (5) verlaengertes Abgelaufen wird Inaktiv und nach expliziter Aktivierung sichtbar; (6) Eigene Inserate ausgeblendet; (7) zwei genehmigte Betriebe koennen Fremdinserate sehen; (8) Radius und fehlende Koordinaten separat testen.
$doc$,updated_at=now() WHERE slug='concept' AND position('## Inseratslaufzeit und Marktplatzsichtbarkeit 0.32.2.2' in body)=0;
UPDATE sk_internal.help_chapters SET body=body || E'\n\n' || $help$## Ablaufdatum und Sichtbarkeit (0.32.2.2)
Inserate bleiben im Marktplatz sichtbar, solange sie Aktiv sind und ihr Bis-Datum noch nicht abgelaufen ist – auch wenn der Von-Termin bereits vorbei ist oder erst in der Zukunft liegt. Nach Ablauf werden sie als Abgelaufen gekennzeichnet und sind nur noch unter Meine Inserate sichtbar. Zur Wiederveroeffentlichung zuerst das Enddatum verlaengern, speichern, dann aktivieren. Manuell Inaktiv bleibt separat. ![Status abgelaufen](screenshot:my-listings-expired-03222)
$help$,updated_at=now() WHERE page_key='my-listings' AND position('## Ablaufdatum und Sichtbarkeit (0.32.2.2)' in body)=0;
COMMIT;
SELECT 'StaffKeeping 0.32.2.2 – Doku aktualisiert' AS status;
