-- StaffKeeping 0.31.7 – Registrierungsentscheidungen + dauerhafte Mail-Warteschlange.
-- Mehrere Anweisungen in einer Transaktion; keine separaten SELECT-Resultsets.
-- PostgreSQL-interne Tabelle wird NICHT über Data API exponiert.
BEGIN;
ALTER TABLE public.sk_businesses DROP CONSTRAINT IF EXISTS sk_businesses_review_state_check;
-- PostgreSQL auto-names the inline CHECK as sk_businesses_review_state_check.
ALTER TABLE public.sk_businesses ADD CONSTRAINT sk_businesses_review_state_check
 CHECK(review_state IN ('draft','submitted','changes_requested','approved','rejected'));

CREATE TABLE IF NOT EXISTS sk_internal.registration_mail_outbox (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 business_id uuid NOT NULL,
 decision text NOT NULL CHECK(decision IN ('approved','changes_requested','rejected')),
 recipient_email text NOT NULL,
 company_name text NOT NULL,
 review_message text,
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','sent','failed')),
 attempts integer NOT NULL DEFAULT 0,
 locked_at timestamptz,
 next_attempt_at timestamptz NOT NULL DEFAULT now(),
 created_at timestamptz NOT NULL DEFAULT now(),
 sent_at timestamptz,
 provider_message_id text,
 last_error text
);
CREATE INDEX IF NOT EXISTS registration_mail_queue_pending
 ON sk_internal.registration_mail_outbox(status,next_attempt_at);
REVOKE ALL ON sk_internal.registration_mail_outbox FROM PUBLIC,anon,authenticated;

-- Queue atomically with registration review, including changes made through the existing RPC.
CREATE OR REPLACE FUNCTION sk_internal.enqueue_registration_mail()
 RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$
BEGIN
 IF NEW.review_state IS DISTINCT FROM OLD.review_state
   AND NEW.review_state IN ('approved','changes_requested','rejected') THEN
  INSERT INTO sk_internal.registration_mail_outbox(business_id,decision,recipient_email,company_name,review_message)
  VALUES(NEW.id, NEW.review_state, NEW.contact_email, NEW.company_name, NEW.review_message);
 END IF;
 RETURN NEW;
END;$fn$;
DROP TRIGGER IF EXISTS sk_registration_mail_queue ON public.sk_businesses;
CREATE TRIGGER sk_registration_mail_queue AFTER UPDATE OF review_state ON public.sk_businesses
 FOR EACH ROW EXECUTE FUNCTION sk_internal.enqueue_registration_mail();

CREATE OR REPLACE FUNCTION public.sk_admin_review_business(p_business_id uuid,p_action text,p_message text DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$
DECLARE b public.sk_businesses%ROWTYPE;
BEGIN
 IF NOT public.sk_is_admin() THEN RAISE EXCEPTION 'Nur Administratoren' USING ERRCODE='42501'; END IF;
 SELECT * INTO b FROM public.sk_businesses WHERE id=p_business_id FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Betrieb unbekannt' USING ERRCODE='22023'; END IF;
 IF b.status<>'Ausstehend' OR b.review_state<>'submitted' THEN
  RAISE EXCEPTION 'Nur eingereichte Anträge entscheiden' USING ERRCODE='22023';
 END IF;
 IF p_action='approve' THEN
  UPDATE public.sk_businesses SET review_state='approved',status='Freigeschaltet',reviewed_at=now(),review_message=NULL,updated_at=now() WHERE id=b.id;
  INSERT INTO sk_internal.business_status_audit(business_id,changed_by,old_status,new_status)
  VALUES(b.id,auth.uid(),b.status,'Freigeschaltet');
  INSERT INTO sk_internal.admin_events(business_id,kind,title,detail,resolved_at,resolved_by)
  VALUES(b.id,'approved','Betrieb freigegeben',b.company_name,now(),auth.uid());
 ELSIF p_action IN ('changes','reject') THEN
  IF length(btrim(coalesce(p_message,'')))<5 THEN
   RAISE EXCEPTION 'Entscheidung bitte begründen (mindestens 5 Zeichen)' USING ERRCODE='22023';
  END IF;
  UPDATE public.sk_businesses SET review_state=CASE WHEN p_action='reject' THEN 'rejected' ELSE 'changes_requested' END,
    reviewed_at=now(),review_message=left(btrim(p_message),3000),updated_at=now() WHERE id=b.id;
  INSERT INTO sk_internal.admin_events(business_id,kind,title,detail,resolved_at,resolved_by)
  VALUES(b.id,CASE WHEN p_action='reject' THEN 'rejected' ELSE 'changes_requested' END,
    CASE WHEN p_action='reject' THEN 'Antrag abgelehnt' ELSE 'Nachbesserung verlangt' END,
    left(btrim(p_message),3000),now(),auth.uid());
 ELSE RAISE EXCEPTION 'Ungültige Prüfaktion' USING ERRCODE='22023';
 END IF;
 UPDATE sk_internal.admin_events SET resolved_at=now(),resolved_by=auth.uid()
 WHERE business_id=b.id AND kind='submitted' AND resolved_at IS NULL;
END;$fn$;

-- Extend pre-existing event constraint while preserving every already-supported kind.
DO $fn$ DECLARE vdef text;
BEGIN
 SELECT pg_get_constraintdef(c.oid) INTO vdef FROM pg_constraint c
 WHERE c.conrelid='sk_internal.admin_events'::regclass AND c.conname='admin_events_kind_check';
 IF vdef IS NOT NULL AND position('''rejected''' in vdef)=0 THEN
  ALTER TABLE sk_internal.admin_events DROP CONSTRAINT admin_events_kind_check;
  ALTER TABLE sk_internal.admin_events ADD CONSTRAINT admin_events_kind_check
  CHECK(kind IN ('submitted','approved','changes_requested','profile_changed','media_changed','location_changed',
  'change_requested','change_approved','change_rejected','blocked','deletion_requested','rejected'));
 END IF;
END;$fn$;

-- service_role only, with atomic row claim to avoid concurrent sends.
CREATE OR REPLACE FUNCTION public.sk_mail_claim_batch(p_limit integer DEFAULT 10)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$
DECLARE result jsonb;
BEGIN
 IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role only' USING ERRCODE='42501'; END IF;
 WITH picked AS (
  SELECT id FROM sk_internal.registration_mail_outbox
  WHERE (status IN ('pending','failed') AND next_attempt_at<=now())
     OR (status='processing' AND locked_at<now()-interval '10 minutes')
  ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT least(greatest(p_limit,1),20)
 ), claimed AS (
  UPDATE sk_internal.registration_mail_outbox q SET status='processing',locked_at=now(),attempts=attempts+1
  FROM picked WHERE q.id=picked.id
  RETURNING q.id,q.decision,q.recipient_email,q.company_name,q.review_message,q.attempts
 ) SELECT coalesce(jsonb_agg(to_jsonb(claimed)),'[]'::jsonb) INTO result FROM claimed;
 RETURN result;
END;$fn$;
CREATE OR REPLACE FUNCTION public.sk_mail_finish(p_id bigint,p_ok boolean,p_message_id text DEFAULT NULL,p_error text DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$
BEGIN
 IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service_role only' USING ERRCODE='42501'; END IF;
 UPDATE sk_internal.registration_mail_outbox SET
  status=CASE WHEN p_ok THEN 'sent' ELSE 'failed' END,
  sent_at=CASE WHEN p_ok THEN now() ELSE NULL END,
  provider_message_id=CASE WHEN p_ok THEN left(coalesce(p_message_id,''),200) ELSE NULL END,
  last_error=CASE WHEN p_ok THEN NULL ELSE left(coalesce(p_error,'Versandfehler'),500) END,
  locked_at=NULL,
  next_attempt_at=CASE WHEN p_ok THEN now() ELSE now()+make_interval(mins=>least(60,2^least(attempts,5)::integer)::integer) END
 WHERE id=p_id AND status='processing';
END;$fn$;
REVOKE ALL ON FUNCTION public.sk_mail_claim_batch(integer) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.sk_mail_finish(bigint,boolean,text,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.sk_mail_claim_batch(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.sk_mail_finish(bigint,boolean,text,text) TO service_role;
COMMIT;
